services:
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    container_name: mysql-carpooling2
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - carpooling-network

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-carpooling
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: carpooling
      RABBITMQ_DEFAULT_PASS: carpooling123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - carpooling-network

volumes:
  mysql_data:
  rabbitmq_data:

networks:
  carpooling-network:
    driver: bridge
