CREATE TABLE IF NOT EXISTS enterprises (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   name TEXT NOT NULL,
   email TEXT NOT NULL UNIQUE,
   password TEXT NOT NULL,
   phone TEXT NULL,
   cif TEXT NULL UNIQUE,
   website TEXT NULL,
   address_line1 TEXT NULL,
   address_line2 TEXT NULL,
   city TEXT NULL,
   province TEXT NULL,
   postal_code TEXT NULL,
   country TEXT NOT NULL DEFAULT 'ES',
   verified INTEGER NOT NULL DEFAULT 0,
   created_at TEXT DEFAULT (CURRENT_TIMESTAMP),
   updated_at TEXT DEFAULT (CURRENT_TIMESTAMP)
);
-- MYSQL
CREATE TABLE `enterprises` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(30) NULL,
  `cif` VARCHAR(50) NULL,
  `website` VARCHAR(255) NULL,
  `address_line1` VARCHAR(255) NULL,
  `address_line2` VARCHAR(255) NULL,
  `city` VARCHAR(120) NULL,
  `province` VARCHAR(120) NULL,
  `postal_code` VARCHAR(20) NULL,
  `country` CHAR(2) NOT NULL DEFAULT 'ES',
  `verified` BOOLEAN NOT NULL DEFAULT FALSE,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_enterprises_email` (`email`),
  UNIQUE KEY `ux_enterprises_cif` (`cif`),
  KEY `idx_enterprises_verified` (`verified`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;