-- Users table based on user.js schema
CREATE TABLE IF NOT EXISTS users (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   username TEXT NOT NULL UNIQUE,
   email TEXT NOT NULL UNIQUE,
   password TEXT NULL,
   img_perfil TEXT,
   name TEXT,
   phone TEXT,
   fecha_nacimiento TEXT NULL,
   dni TEXT NULL UNIQUE,
   genero TEXT NULL CHECK (genero IN ('Masculino','Femenino','Otro')),
   stripe_account TEXT,
   stripe_customer_account TEXT,
   ciudad TEXT NULL,
   provincia TEXT NULL,
   codigo_postal TEXT NULL,
   direccion TEXT NULL,
   onboarding_ended INTEGER NOT NULL DEFAULT 0,
   about_me TEXT,
   auth_method TEXT CHECK (auth_method IN ('password', 'google', 'other')) NOT NULL DEFAULT 'password',
   google_id TEXT NULL,
   created_at TEXT DEFAULT (CURRENT_TIMESTAMP),
   updated_at TEXT DEFAULT (CURRENT_TIMESTAMP)
);

--mysql
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NULL,
    img_perfil VARCHAR(255),
    name VARCHAR(150),
    phone VARCHAR(20),
    fecha_nacimiento DATE NULL,
    dni VARCHAR(20) NULL UNIQUE,
    genero ENUM('Masculino', 'Femenino', 'Otro') NULL,
    stripe_account VARCHAR(255),
    stripe_customer_account VARCHAR(255),
    ciudad VARCHAR(100) NULL,
    provincia VARCHAR(100) NULL,
    codigo_postal VARCHAR(20) NULL,
    direccion VARCHAR(255) NULL,
    onboarding_ended TINYINT(1) NOT NULL DEFAULT 0,
    about_me TEXT,
    auth_method ENUM('password', 'google', 'other') NOT NULL DEFAULT 'password',
    google_id VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;